branches:
  only:
    - main
matrix:
  fast_finish: true
  allow_failures:
  - env: ALLOW_FAILURES=1
  include:
  - language: ruby
    ruby: 2.3
    script:
      - DO_NOT_CHECK_HTTP_LINKS=1 ruby check-markdown-links.rb
  - language: rust
    rust: nightly-2020-03-01
    # per https://levans.fr/rust_travis_cache.html
    cache:
      directories:
        - /home/travis/.cargo
    before_cache:
      - rm -rf /home/travis/.cargo/registry
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cd ../spacesuit
    - cargo fmt --all -- --check
    - cargo test
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONOTMATCHANYBENCHMARK"
    - cd ../readerwriter
    - cargo fmt --all -- --check
    - cargo test
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONOTMATCHANYBENCHMARK"
    - cd ../zkvm
    - cargo fmt --all -- --check
    - cargo test
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONOTMATCHANYBENCHMARK"
    - cd ../blockchain
    - cargo fmt --all -- --check
    - cargo test
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONOTMATCHANYBENCHMARK"
    - cd ../starsig
    - cargo fmt --all -- --check
    - cargo test
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONOTMATCHANYBENCHMARK"
    - cd ../musig
    - cargo fmt --all -- --check
    - cargo test
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONOTMATCHANYBENCHMARK"
    - cd ../keytree
    - cargo fmt --all -- --check
    - cargo test
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONOTMATCHANYBENCHMARK"
    - cd ../p2p
    - cargo fmt --all -- --check
    - cargo test
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONOTMATCHANYBENCHMARK"
    - cd ../token
    - cargo fmt --all -- --check
    - cargo test
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONOTMATCHANYBENCHMARK"
    - cd ../accounts
    - cargo fmt --all -- --check
    - cargo test
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONOTMATCHANYBENCHMARK"
    - cd ../demo
    - cargo fmt --all -- --check
    - cargo check
