language: go
go:
  - '1.11'
branches:
  only:
    - main
install: true
script:
  - go test -v ./... -timeout 60m
  - go vet ./...
  - test `gofmt -s -l ./slidechain | grep -vF /vendor/ | wc -l` -eq 0
