branches:
  only:
    - main
matrix:
  fast_finish: true
  include:
  - language: ruby
    ruby: 2.3
    script:
      - DO_NOT_CHECK_HTTP_LINKS=1 ruby check-markdown-links.rb
  - language: rust
    rust: nightly-2020-03-01
    # per https://levans.fr/rust_travis_cache.html
    cache:
      directories:
        - $HOME/.cargo
        - $HOME/.rustup
    before_cache:
      - rm -rf $HOME/.cargo/registry
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --check
  - language: rust
    rust: nightly-2020-03-01
    # per https://levans.fr/rust_travis_cache.html
    cache:
      directories:
        - $HOME/.cargo
        - $HOME/.rustup
    before_cache:
      - rm -rf $HOME/.cargo/registry
    script:
    - cargo test
  - language: rust
    rust: nightly-2020-03-01
    # per https://levans.fr/rust_travis_cache.html
    cache:
      directories:
        - $HOME/.cargo
        - $HOME/.rustup
    before_cache:
      - rm -rf $HOME/.cargo/registry
    script:
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONOTMATCHANYBENCHMARK"
