name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cargo-fmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cargo fmt
      run: cargo fmt --all -- --check

  cargo-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cargo test
      run: cargo test

  cargo-bench:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build benchmarks
      run: cargo bench DONTRUNBENCHMARKS

  check-demo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install the nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Build
      run: cd demo && cargo build
